### PR TITLE
Add chart image to readme

### PR DESCRIPTION
**Pull request by harlantwood**
Same idea as outlined in https://github.com/AstroDraw/AstroChart/issues/70 -- to immediately give the user the visual idea of what is possible.

You can see the rendered version of the README with image here: https://github.com/harlantwood/AstroChart/tree/patch-1?tab=readme-ov-file#astrochart

### CODE REVIEW

**Comment by afucher** [comment]
Hey @harlantwood ,
From where this image is? https://github.com/AstroDraw/AstroChart/assets/38769/0adc6822-7145-4e33-9e0b-53065e96d61a 
Sorry, if I'm missing something, but I did not found where this image is.

**Comment by harlantwood** [comment]
> Hey @harlantwood ,
> From where this image is? https://github.com/AstroDraw/AstroChart/assets/38769/0adc6822-7145-4e33-9e0b-53065e96d61a
> Sorry, if I'm missing something, but I did not found where this image is.

I made the PR via GitHub UI, uploaded the image in the UI, and GitHub gave it that URL… so, GitHub magic. ✨

**Comment by afucher** [comment]
> I made the PR via GitHub UI, uploaded the image in the UI, and GitHub gave it that URL… so, GitHub magic. ✨
Hmmm... so I fhink that is better to upload the image to the repo in a folder and reference it in the README.

**Review by afucher — CHANGES_REQUESTED** [review]
Add the image to the repo, so we do not depend on Github magic ✨

**Comment by harlantwood** [comment]
Added the image in a separate PR: #75.

We should merge that one first.

After that, the branch behind *this* PR will show the image correctly in its readme when clicking this link:

https://github.com/harlantwood/AstroChart/tree/patch-1#example

What you should see there will be something like:

Screen Shot 2024-03-30 at 10 54 52 PM

**Pull request merged**
