### PR TITLE
Fix universe and points drawing order

### PR DESCRIPTION
**Pull request by ilyai**
Draw the universe and points last so they appear on top of axes and circles whenever they cross, since they're more important

### CODE REVIEW

**Comment by afucher** [comment]
Hey @ilyai , all good?
Can you please share some images about how your change is affecting the drawing? Like, before and after.

**Comment by ilyai** [comment]
Hi @afucher! Yep, here it is.

**Before:**
Screen Shot 2022-10-17 at 22 47 27

**After:**
Screen Shot 2022-10-17 at 22 44 36

As you can see the difference is quite clear, especially when the colors are different.

**Comment by afucher** [comment]
LGTM! Thanks for your contribution :)

**Comment by afucher** [comment]
@ilyai just to let you know, I have to revert this PR. It introduced a behavior, that is a breaking change to the existing one. I describe it better in the #40 , that I opened to think how we can handle what you propose here, and the existing behavior.
Sorry for did not catch this, and merged your PR, and now have to revert it. Please feel free to add your opinions in the #40 issue.

**Pull request merged**
